CREATE TABLE [Insurance].[ChatNote]
(
	[ID] BIGINT IDENTITY NOT NULL,
	[ID_Chat] BIGINT NOT NULL,
	[ID_User] NVARCHAR(128) NOT NULL,
	[Note] NVARCHAR(MAX) NULL,
	[CreateDate] DATETIME2 NOT NULL,
	[LastUpdateDate] DATETIME2 NOT NULL,
    CONSTRAINT [PK_ChatNote] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_ChatNote_Chat] FOREIGN KEY([ID_Chat]) REFERENCES [Insurance].[Chat] ([ID]) ON DELETE CASCADE,
	CONSTRAINT [FK_ChatNote_AspNetUsers] FOREIGN KEY([ID_User]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE
)
