CREATE TABLE [Insurance].[PostImage]
(
	[ID] BIGINT IDENTITY NOT NULL,
	--[ID_User] NVARCHAR(128) NOT NULL,
	[ID_Post] BIGINT NOT NULL,
	[FileName] NVARCHAR(256) NULL,
	[FileExtension] NVARCHAR(8) NULL,
	[Image] IMAGE NOT NULL,
	[Type] NVARCHAR(8) NULL,
	[Date] DATETIME2 NOT NULL,
	[Active] BIT NOT NULL DEFAULT 1,	
    CONSTRAINT [PK_PostImage] PRIMARY KEY CLUSTERED ([ID] ASC),
	--CONSTRAINT [FK_PostImage_AspNetUsers] FOREIGN KEY([ID_User]) REFERENCES [dbo].[AspNetUsers] ([Id]),
	CONSTRAINT [FK_PostImage_Post] FOREIGN KEY([ID_Post]) REFERENCES [Insurance].[Post] ([ID])
)
