CREATE TABLE [Insurance].[PostReported]
(
	[ID] BIGINT IDENTITY NOT NULL,
	[ID_User] NVARCHAR(128) NOT NULL,
	[ID_Post] BIGINT NOT NULL,
	[Reported] BIT NOT NULL DEFAULT 1,
	[Reason] NVARCHAR(512) NOT NULL,
	[Date] DATETIME2 NOT NULL,
    CONSTRAINT [PK_PostReported] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_PostReported_AspNetUsers] FOREIGN KEY([ID_User]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_PostReported_Post] FOREIGN KEY([ID_Post]) REFERENCES [Insurance].[Post] ([ID]) ON DELETE CASCADE
)
