CREATE TABLE [Insurance].[SystemLog]
(
	[ID] BIGINT IDENTITY NOT NULL, 
    [LogDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [Level] NVARCHAR(64) NOT NULL,
    [ID_User] NVARCHAR(128) NULL, 
	[Title] NVARCHAR(128) NULL,
	[Message] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_SystemLog] PRIMARY KEY CLUSTERED ([ID] ASC)
)

