//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InsuranceWebsite.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre nós.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre mim.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione um comentário....
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Amigo.
        /// </summary>
        public static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Banner.
        /// </summary>
        public static string AddNewBanner {
            get {
                return ResourceManager.GetString("AddNewBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Alertas.
        /// </summary>
        public static string AlertsManagement {
            get {
                return ResourceManager.GetString("AlertsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associado ou Premium.
        /// </summary>
        public static string ASSOCIATED_PREMIUM {
            get {
                return ResourceManager.GetString("ASSOCIATED_PREMIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Banners.
        /// </summary>
        public static string BannersManagement {
            get {
                return ResourceManager.GetString("BannersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de banner.
        /// </summary>
        public static string BannerType {
            get {
                return ResourceManager.GetString("BannerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação Básica.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos de Conversa.
        /// </summary>
        public static string ChatGroups {
            get {
                return ResourceManager.GetString("ChatGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique o seu e-mail para confirmar o registo e ativar o acesso ao portal..
        /// </summary>
        public static string CheckYourEmailToGetAccess {
            get {
                return ResourceManager.GetString("CheckYourEmailToGetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da clínica.
        /// </summary>
        public static string ClinicName {
            get {
                return ResourceManager.GetString("ClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código é obrigatório.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentários nas suas publicações.
        /// </summary>
        public static string CommentsOnYourPosts {
            get {
                return ResourceManager.GetString("CommentsOnYourPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da empresa de construção.
        /// </summary>
        public static string ConstructionCompanyName {
            get {
                return ResourceManager.GetString("ConstructionCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de contacto.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação de Contacto.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar novo banner.
        /// </summary>
        public static string CreateNewBanner {
            get {
                return ResourceManager.GetString("CreateNewBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de registo.
        /// </summary>
        public static string DateJoined {
            get {
                return ResourceManager.GetString("DateJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dias atrás.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento.
        /// </summary>
        public static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data limite.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar banner.
        /// </summary>
        public static string EditBanner {
            get {
                return ResourceManager.GetString("EditBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail é obrigatório.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o seu e-mail.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu a sua palavra-passe?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da oficina.
        /// </summary>
        public static string GarageName {
            get {
                return ResourceManager.GetString("GarageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do reparador de electrodomésticos.
        /// </summary>
        public static string HomeApplianceRepairName {
            get {
                return ResourceManager.GetString("HomeApplianceRepairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falar Seguros.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas atrás.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissional de Seguros.
        /// </summary>
        public static string INSURANCE_PROFESSIONAL {
            get {
                return ResourceManager.GetString("INSURANCE_PROFESSIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da seguradora.
        /// </summary>
        public static string InsuranceContactName {
            get {
                return ResourceManager.GetString("InsuranceContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativa de login inválida!.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostos nas suas publicações.
        /// </summary>
        public static string LikesOnYourPosts {
            get {
                return ResourceManager.GetString("LikesOnYourPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concelho.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar Sessão.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicou um novo post.
        /// </summary>
        public static string MadePost {
            get {
                return ResourceManager.GetString("MadePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falar Seguros - Mensagens.
        /// </summary>
        public static string MessagesPageTitle {
            get {
                return ResourceManager.GetString("MessagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos atrás.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemovel #1.
        /// </summary>
        public static string MobilePhone_1 {
            get {
                return ResourceManager.GetString("MobilePhone_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemovel #2.
        /// </summary>
        public static string MobilePhone_2 {
            get {
                return ResourceManager.GetString("MobilePhone_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Negócios.
        /// </summary>
        public static string MyBusinesses {
            get {
                return ResourceManager.GetString("MyBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem notificações.
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador Comum.
        /// </summary>
        public static string NORMAL_USER {
            get {
                return ResourceManager.GetString("NORMAL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string NotificationsPageTitle {
            get {
                return ResourceManager.GetString("NotificationsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente oficial.
        /// </summary>
        public static string OfficialAgent {
            get {
                return ResourceManager.GetString("OfficialAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password antiga.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcerias.
        /// </summary>
        public static string Partnerships {
            get {
                return ResourceManager.GetString("Partnerships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password é obrigatória.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidade.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica de Privacidade.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falar Seguros - Perfil.
        /// </summary>
        public static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        public static string Regist {
            get {
                return ResourceManager.GetString("Regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de registo.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-se de mim?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-se deste browser?.
        /// </summary>
        public static string RememberThisBrowser {
            get {
                return ResourceManager.GetString("RememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Amigo.
        /// </summary>
        public static string RemoveFriend {
            get {
                return ResourceManager.GetString("RemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil é obrigatório.
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Perfis.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar clínicas.
        /// </summary>
        public static string SearchClinics {
            get {
                return ResourceManager.GetString("SearchClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar empresas de construção/remodelação.
        /// </summary>
        public static string SearchConstructionCompanies {
            get {
                return ResourceManager.GetString("SearchConstructionCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar oficinas.
        /// </summary>
        public static string SearchGarages {
            get {
                return ResourceManager.GetString("SearchGarages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar reparadores de electrodomésticos.
        /// </summary>
        public static string SearchHomeApplianceRepair {
            get {
                return ResourceManager.GetString("SearchHomeApplianceRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar contactos de seguradoras.
        /// </summary>
        public static string SearchInsuranceContacts {
            get {
                return ResourceManager.GetString("SearchInsuranceContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundos atrás.
        /// </summary>
        public static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Seleccione o perfil&gt;.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Mensagem.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar data de nascimento.
        /// </summary>
        public static string ShowBirthDate {
            get {
                return ResourceManager.GetString("ShowBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar informação de contacto.
        /// </summary>
        public static string ShowContactInformation {
            get {
                return ResourceManager.GetString("ShowContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar o nome de utilizador.
        /// </summary>
        public static string ShowDisplayName {
            get {
                return ResourceManager.GetString("ShowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar estado online.
        /// </summary>
        public static string ShowOnlineStatus {
            get {
                return ResourceManager.GetString("ShowOnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatisticas.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone #1.
        /// </summary>
        public static string Telephone_1 {
            get {
                return ResourceManager.GetString("Telephone_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone #2.
        /// </summary>
        public static string Telephone_2 {
            get {
                return ResourceManager.GetString("Telephone_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos de Utilização.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado pelo seu registo no portal Falar Seguros..
        /// </summary>
        public static string ThanksForRegister {
            get {
                return ResourceManager.GetString("ThanksForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicou uma foto.
        /// </summary>
        public static string UploadedPhoto {
            get {
                return ResourceManager.GetString("UploadedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicou um vídeo.
        /// </summary>
        public static string UploadedVideo {
            get {
                return ResourceManager.GetString("UploadedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de Utilizador.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Utilizadores.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvindo.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partilhe e conheça as oportunidades na mediação de seguros!.
        /// </summary>
        public static string WelcomeAbout {
            get {
                return ResourceManager.GetString("WelcomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ao portal Falar Seguros.
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O que pretende publicar hoje?.
        /// </summary>
        public static string WhatsInYourMindToday {
            get {
                return ResourceManager.GetString("WhatsInYourMindToday", resourceCulture);
            }
        }
    }
}
