//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InsuranceWebsite.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre nós.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre mim.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aceitou o seu pedido de amizade.
        /// </summary>
        public static string AcceptedYourFriendRequest {
            get {
                return ResourceManager.GetString("AcceptedYourFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceitar pedido.
        /// </summary>
        public static string AcceptRequest {
            get {
                return ResourceManager.GetString("AcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione um comentário....
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar email/dominio.
        /// </summary>
        public static string AddEmailOrDomain {
            get {
                return ResourceManager.GetString("AddEmailOrDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Amigo.
        /// </summary>
        public static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Banner.
        /// </summary>
        public static string AddNewBanner {
            get {
                return ResourceManager.GetString("AddNewBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string ADMINISTRATOR {
            get {
                return ResourceManager.GetString("ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Alertas.
        /// </summary>
        public static string AlertsManagement {
            get {
                return ResourceManager.GetString("AlertsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de e-mails/dominios autorizados.
        /// </summary>
        public static string AllowedEmailDomains {
            get {
                return ResourceManager.GetString("AllowedEmailDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FalarSeguros.pt.
        /// </summary>
        public static string ApplicationNAme {
            get {
                return ResourceManager.GetString("ApplicationNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APROSE.
        /// </summary>
        public static string APROSE {
            get {
                return ResourceManager.GetString("APROSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página da APROSE.
        /// </summary>
        public static string AprosePage {
            get {
                return ResourceManager.GetString("AprosePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APS.
        /// </summary>
        public static string APS {
            get {
                return ResourceManager.GetString("APS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página da APS.
        /// </summary>
        public static string ApsPage {
            get {
                return ResourceManager.GetString("ApsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende activar a empresa?.
        /// </summary>
        public static string AreYouSureToActivateCompany {
            get {
                return ResourceManager.GetString("AreYouSureToActivateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende activar o utilizador?.
        /// </summary>
        public static string AreYouSureToActivateUser {
            get {
                return ResourceManager.GetString("AreYouSureToActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende desactivar a empresa?.
        /// </summary>
        public static string AreYouSureToDeactivateCompany {
            get {
                return ResourceManager.GetString("AreYouSureToDeactivateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende desactivar o utilizador?.
        /// </summary>
        public static string AreYouSureToDeactivateUser {
            get {
                return ResourceManager.GetString("AreYouSureToDeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende apagar?.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASF.
        /// </summary>
        public static string ASF {
            get {
                return ResourceManager.GetString("ASF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página da ASF.
        /// </summary>
        public static string AsfPage {
            get {
                return ResourceManager.GetString("AsfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador Premium.
        /// </summary>
        public static string ASSOCIATED_PREMIUM {
            get {
                return ResourceManager.GetString("ASSOCIATED_PREMIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Banners.
        /// </summary>
        public static string BannersManagement {
            get {
                return ResourceManager.GetString("BannersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de banner.
        /// </summary>
        public static string BannerType {
            get {
                return ResourceManager.GetString("BannerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação Básica.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos de Conversa.
        /// </summary>
        public static string ChatGroups {
            get {
                return ResourceManager.GetString("ChatGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversações.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversação com {0}.
        /// </summary>
        public static string ChatWith {
            get {
                return ResourceManager.GetString("ChatWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique o seu e-mail para confirmar o registo e ativar o acesso ao portal..
        /// </summary>
        public static string CheckYourEmailToGetAccess {
            get {
                return ResourceManager.GetString("CheckYourEmailToGetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da clínica.
        /// </summary>
        public static string ClinicName {
            get {
                return ResourceManager.GetString("ClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código é obrigatório.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comentou a sua publicação.
        /// </summary>
        public static string CommentedOnYourPost {
            get {
                return ResourceManager.GetString("CommentedOnYourPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentários nas suas publicações.
        /// </summary>
        public static string CommentsOnYourPosts {
            get {
                return ResourceManager.GetString("CommentsOnYourPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguradoras com que trabalha.
        /// </summary>
        public static string CompaniesWorkingWith {
            get {
                return ResourceManager.GetString("CompaniesWorkingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Directório Construções e Remodelações.
        /// </summary>
        public static string ConstructionCompaniesManagement {
            get {
                return ResourceManager.GetString("ConstructionCompaniesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da empresa de construção.
        /// </summary>
        public static string ConstructionCompanyName {
            get {
                return ResourceManager.GetString("ConstructionCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de contacto.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação de Contacto.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilização de Cookies.
        /// </summary>
        public static string CookieUsagePolicy {
            get {
                return ResourceManager.GetString("CookieUsagePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concelho.
        /// </summary>
        public static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar novo banner.
        /// </summary>
        public static string CreateNewBanner {
            get {
                return ResourceManager.GetString("CreateNewBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar empresa.
        /// </summary>
        public static string CreateNewCompany {
            get {
                return ResourceManager.GetString("CreateNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar novo utilizador.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em discussão.
        /// </summary>
        public static string CurrentDiscussions {
            get {
                return ResourceManager.GetString("CurrentDiscussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica de Dados.
        /// </summary>
        public static string DataPolicy {
            get {
                return ResourceManager.GetString("DataPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de registo.
        /// </summary>
        public static string DateJoined {
            get {
                return ResourceManager.GetString("DateJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dia atrás.
        /// </summary>
        public static string DayAgo {
            get {
                return ResourceManager.GetString("DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dias atrás.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento.
        /// </summary>
        public static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data limite.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar banner.
        /// </summary>
        public static string EditBanner {
            get {
                return ResourceManager.GetString("EditBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar empresa.
        /// </summary>
        public static string EditCompany {
            get {
                return ResourceManager.GetString("EditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Utilizador.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de registo.
        /// </summary>
        public static string EmailRegisterConfirmation {
            get {
                return ResourceManager.GetString("EmailRegisterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail é obrigatório.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o seu e-mail.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceste-te da tua conta?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foram encontradas {0} oficinas.
        /// </summary>
        public static string FoundGarages {
            get {
                return ResourceManager.GetString("FoundGarages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foram encontradas {0} clínicas.
        /// </summary>
        public static string FoundMedicalClinics {
            get {
                return ResourceManager.GetString("FoundMedicalClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Directório Automóvel.
        /// </summary>
        public static string GarageCompaniesManagement {
            get {
                return ResourceManager.GetString("GarageCompaniesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da oficina.
        /// </summary>
        public static string GarageName {
            get {
                return ResourceManager.GetString("GarageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esconder.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Directório Electrodomésticos e Electrónica.
        /// </summary>
        public static string HomeApplianceRepairCompaniesManagement {
            get {
                return ResourceManager.GetString("HomeApplianceRepairCompaniesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do reparador de electrodomésticos.
        /// </summary>
        public static string HomeApplianceRepairName {
            get {
                return ResourceManager.GetString("HomeApplianceRepairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falar Seguros.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horas atrás.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RH Seguros.
        /// </summary>
        public static string HRInsurances {
            get {
                return ResourceManager.GetString("HRInsurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar pedido.
        /// </summary>
        public static string IgnoreRequest {
            get {
                return ResourceManager.GetString("IgnoreRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em discussão.
        /// </summary>
        public static string InDiscussion {
            get {
                return ResourceManager.GetString("InDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediador de Seguros.
        /// </summary>
        public static string INSURANCE_PROFESSIONAL {
            get {
                return ResourceManager.GetString("INSURANCE_PROFESSIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Seguradoras.
        /// </summary>
        public static string InsuranceContactCompaniesManagement {
            get {
                return ResourceManager.GetString("InsuranceContactCompaniesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da seguradora.
        /// </summary>
        public static string InsuranceContactName {
            get {
                return ResourceManager.GetString("InsuranceContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativa de login inválida!.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gostou da sua publicação.
        /// </summary>
        public static string LikedYourPost {
            get {
                return ResourceManager.GetString("LikedYourPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostos nas suas publicações.
        /// </summary>
        public static string LikesOnYourPosts {
            get {
                return ResourceManager.GetString("LikesOnYourPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concelho.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sessão.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar sessão.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicou um novo post.
        /// </summary>
        public static string MadePost {
            get {
                return ResourceManager.GetString("MadePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Directório Saúde.
        /// </summary>
        public static string MedicalClinicCompaniesManagement {
            get {
                return ResourceManager.GetString("MedicalClinicCompaniesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falar Seguros - Mensagens.
        /// </summary>
        public static string MessagesPageTitle {
            get {
                return ResourceManager.GetString("MessagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutos atrás.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner principal (versão mobile).
        /// </summary>
        public static string MOBILE_PRINCIPAL_BANNER {
            get {
                return ResourceManager.GetString("MOBILE_PRINCIPAL_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner secundário (versão mobile).
        /// </summary>
        public static string MOBILE_SECONDARY_BANNER {
            get {
                return ResourceManager.GetString("MOBILE_SECONDARY_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemovel #1.
        /// </summary>
        public static string MobilePhone_1 {
            get {
                return ResourceManager.GetString("MobilePhone_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemovel #2.
        /// </summary>
        public static string MobilePhone_2 {
            get {
                return ResourceManager.GetString("MobilePhone_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Negócios.
        /// </summary>
        public static string MyBusinesses {
            get {
                return ResourceManager.GetString("MyBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo da nova publicação da APROSE.
        /// </summary>
        public static string NewAprosePost {
            get {
                return ResourceManager.GetString("NewAprosePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo da nova publicação da APS.
        /// </summary>
        public static string NewApsPost {
            get {
                return ResourceManager.GetString("NewApsPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo da nova publicação da ASF.
        /// </summary>
        public static string NewAsfPost {
            get {
                return ResourceManager.GetString("NewAsfPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo do novo tema em discussão.
        /// </summary>
        public static string NewCurrentDiscussion {
            get {
                return ResourceManager.GetString("NewCurrentDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova palavra-passe.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguinte.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        public static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione uma conversação para listar as respectivas mensagens.
        /// </summary>
        public static string NoActiveChatSelected {
            get {
                return ResourceManager.GetString("NoActiveChatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem publicações da ASF.
        /// </summary>
        public static string NoAfsPosts {
            get {
                return ResourceManager.GetString("NoAfsPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem publicações da APROSE.
        /// </summary>
        public static string NoAprosePosts {
            get {
                return ResourceManager.GetString("NoAprosePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem publicações da APS.
        /// </summary>
        public static string NoApsPosts {
            get {
                return ResourceManager.GetString("NoApsPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem conversações.
        /// </summary>
        public static string NoChats {
            get {
                return ResourceManager.GetString("NoChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem temas em discussão.
        /// </summary>
        public static string NoCurrentDiscussions {
            get {
                return ResourceManager.GetString("NoCurrentDiscussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De momento não possui amigos.
        /// </summary>
        public static string NoFriends {
            get {
                return ResourceManager.GetString("NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De momento não possui notificações.
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador Comum.
        /// </summary>
        public static string NORMAL_USER {
            get {
                return ResourceManager.GetString("NORMAL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string NotificationsPageTitle {
            get {
                return ResourceManager.GetString("NotificationsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agora.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente oficial.
        /// </summary>
        public static string OfficialAgent {
            get {
                return ResourceManager.GetString("OfficialAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parceiro oficial.
        /// </summary>
        public static string OfficialPartner {
            get {
                return ResourceManager.GetString("OfficialPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-passe anterior.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho da página.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freguesia.
        /// </summary>
        public static string Parish {
            get {
                return ResourceManager.GetString("Parish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcerias.
        /// </summary>
        public static string Partnerships {
            get {
                return ResourceManager.GetString("Partnerships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-passe é obrigatória.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidade.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica de Privacidade.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Mediador (ASF).
        /// </summary>
        public static string ProfessionalNumber {
            get {
                return ResourceManager.GetString("ProfessionalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falar Seguros - Perfil.
        /// </summary>
        public static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo.
        /// </summary>
        public static string Regist {
            get {
                return ResourceManager.GetString("Regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regista-te.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} o portal Falar Seguros dá-lhe as boas vindas!&lt;BR/&gt;Obrigado por se registar! Queira por favor clicar no seguinte link para concluir o seu processo de registo e usufruir da plataforma Falar Seguros: &lt;a href=&apos;{1}&apos; title=&apos;Confirmação Registo&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string RegisterConfirmationMessage {
            get {
                return ResourceManager.GetString("RegisterConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de registo.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-se de mim?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-se deste browser?.
        /// </summary>
        public static string RememberThisBrowser {
            get {
                return ResourceManager.GetString("RememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover email/dominio.
        /// </summary>
        public static string RemoveEmailOrDomain {
            get {
                return ResourceManager.GetString("RemoveEmailOrDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Amigo.
        /// </summary>
        public static string RemoveFriend {
            get {
                return ResourceManager.GetString("RemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil é obrigatório.
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Perfis.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negócios Seguros.
        /// </summary>
        public static string SafeBusinesses {
            get {
                return ResourceManager.GetString("SafeBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directório Saúde.
        /// </summary>
        public static string SearchClinics {
            get {
                return ResourceManager.GetString("SearchClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directório Construções e Remodelações.
        /// </summary>
        public static string SearchConstructionCompanies {
            get {
                return ResourceManager.GetString("SearchConstructionCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directório Automóvel.
        /// </summary>
        public static string SearchGarages {
            get {
                return ResourceManager.GetString("SearchGarages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directório Electrodomésticos e Electrónica.
        /// </summary>
        public static string SearchHomeApplianceRepair {
            get {
                return ResourceManager.GetString("SearchHomeApplianceRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguradoras.
        /// </summary>
        public static string SearchInsuranceContacts {
            get {
                return ResourceManager.GetString("SearchInsuranceContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundos atrás.
        /// </summary>
        public static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione o concelho.
        /// </summary>
        public static string SelectCounty {
            get {
                return ResourceManager.GetString("SelectCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione o distrito.
        /// </summary>
        public static string SelectDistrict {
            get {
                return ResourceManager.GetString("SelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Seleccione o perfil&gt;.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione serviço.
        /// </summary>
        public static string SelectService {
            get {
                return ResourceManager.GetString("SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Mensagem.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enviou-lhe um pedido de amizade.
        /// </summary>
        public static string SentYouFriendRequest {
            get {
                return ResourceManager.GetString("SentYouFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar data de nascimento.
        /// </summary>
        public static string ShowBirthDate {
            get {
                return ResourceManager.GetString("ShowBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar informação de contacto.
        /// </summary>
        public static string ShowContactInformation {
            get {
                return ResourceManager.GetString("ShowContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar o nome de utilizador.
        /// </summary>
        public static string ShowDisplayName {
            get {
                return ResourceManager.GetString("ShowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listando registos {0} a {1} de {2}.
        /// </summary>
        public static string ShowingGridEntries {
            get {
                return ResourceManager.GetString("ShowingGridEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar estado online.
        /// </summary>
        public static string ShowOnlineStatus {
            get {
                return ResourceManager.GetString("ShowOnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal FalarSeguros.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicidade.
        /// </summary>
        public static string Sponsored {
            get {
                return ResourceManager.GetString("Sponsored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatisticas.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone #1.
        /// </summary>
        public static string Telephone_1 {
            get {
                return ResourceManager.GetString("Telephone_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone #2.
        /// </summary>
        public static string Telephone_2 {
            get {
                return ResourceManager.GetString("Telephone_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos de Utilização.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado pelo seu registo no portal Falar Seguros..
        /// </summary>
        public static string ThanksForRegister {
            get {
                return ResourceManager.GetString("ThanksForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicou uma foto.
        /// </summary>
        public static string UploadedPhoto {
            get {
                return ResourceManager.GetString("UploadedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publicou um vídeo.
        /// </summary>
        public static string UploadedVideo {
            get {
                return ResourceManager.GetString("UploadedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de Utilizador.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Utilizadores.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner principal (versão web).
        /// </summary>
        public static string WEB_PRINCIPAL_BANNER {
            get {
                return ResourceManager.GetString("WEB_PRINCIPAL_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner secundário (versão web).
        /// </summary>
        public static string WEB_SECONDARY_BANNER {
            get {
                return ResourceManager.GetString("WEB_SECONDARY_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvindo.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partilhe e conheça as oportunidades na mediação de seguros!.
        /// </summary>
        public static string WelcomeAbout {
            get {
                return ResourceManager.GetString("WelcomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ao portal Falar Seguros.
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O que pretende publicar hoje?.
        /// </summary>
        public static string WhatsInYourMindToday {
            get {
                return ResourceManager.GetString("WhatsInYourMindToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete a informação do seu perfil.
        /// </summary>
        public static string YouNeedCompleteYourProfile {
            get {
                return ResourceManager.GetString("YouNeedCompleteYourProfile", resourceCulture);
            }
        }
    }
}
