//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSocialNetworkDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public long ID { get; set; }
        public long ID_Banner_Type { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string Url { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public bool Active { get; set; }
    
        public virtual BannerType BannerType { get; set; }
    }
}
