//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSocialNetworkDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyWorkingWith
    {
        public long ID { get; set; }
        public string ID_User { get; set; }
        public long ID_CompanyType { get; set; }
        public long ID_Company { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public bool Active { get; set; }
        public int Order { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CompanyType CompanyType { get; set; }
    }
}
