//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSocialNetworkDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long ID { get; set; }
        public Nullable<long> ID_Profile { get; set; }
        public Nullable<long> ID_Garage { get; set; }
        public Nullable<long> ID_HomeApplianceRepair { get; set; }
        public Nullable<long> ID_MedicalClinic { get; set; }
        public Nullable<long> ID_ConstructionCompany { get; set; }
        public Nullable<long> ID_InsuranceCompanyContact { get; set; }
        public long ID_PaymentType { get; set; }
        public long ID_PaymentStatus { get; set; }
        public System.Guid Payment_GUID { get; set; }
        public string ep_cin { get; set; }
        public string ep_user { get; set; }
        public string ep_entity { get; set; }
        public string ep_ref_type { get; set; }
        public string ep_type { get; set; }
        public string ep_currency { get; set; }
        public string ep_country { get; set; }
        public string ep_language { get; set; }
        public string ep_reference { get; set; }
        public string ep_value { get; set; }
        public string t_value { get; set; }
        public string t_key { get; set; }
        public string o_name { get; set; }
        public string o_description { get; set; }
        public string o_obs { get; set; }
        public string o_mobile { get; set; }
        public string o_email { get; set; }
        public string o_max_date { get; set; }
        public string ep_partner { get; set; }
        public string ep_rec { get; set; }
        public string ep_rec_freq { get; set; }
        public string ep_rec_url { get; set; }
        public string ep_status { get; set; }
        public string ep_message { get; set; }
        public string ep_original_value { get; set; }
        public string ep_link { get; set; }
        public string ep_link_rp_cc { get; set; }
        public string ep_link_rp_dd { get; set; }
        public string ep_k1 { get; set; }
        public string ep_periodicity { get; set; }
        public string ep_boleto { get; set; }
        public string ep_key { get; set; }
        public string ep_doc { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> ExpiracyDate { get; set; }
        public bool Active { get; set; }
        public string Message { get; set; }
    
        public virtual ConstructionCompany ConstructionCompany { get; set; }
        public virtual Garage Garage { get; set; }
        public virtual HomeApplianceRepair HomeApplianceRepair { get; set; }
        public virtual InsuranceCompanyContact InsuranceCompanyContact { get; set; }
        public virtual MedicalClinic MedicalClinic { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
