//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSocialNetworkDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostImage
    {
        public long ID { get; set; }
        public long ID_Post { get; set; }
        public byte[] Image { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public bool Active { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
