
/* ADMINISTRATOR */
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','USERS_MANAGEMENT',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','ROLES_MANAGEMENT',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','ALERTS_MANAGEMENT',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','BANNERS_MANAGEMENT',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','COMPANIES_MANAGEMENT',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','COMPANY_FAVORITE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','MESSAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','NOTIFICATIONS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','ADD_FRIEND_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','NEW_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','LIKE_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','TIMELINE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','COMMENT_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','PROFILE_INFO_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','FRIENDS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','SEARCH_GARAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','SEARCH_CLINICS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','SEARCH_CONSTRUCTIONCOMPANIES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','SEARCH_APPLIANCEREPAIR_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','SEARCH_INSURANCECONTACTS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','SETTINGS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','CURRENT_DISCUSSIONS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','NEW_CURRENT_DISCUSSION_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','ASF_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','NEW_ASF_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','APS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','NEW_APS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','APROSE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('1','NEW_APROSE_FUNCTIONALITY',1);

/* NORMAL_USER */
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','USERS_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','ROLES_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','ALERTS_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','COMPANY_FAVORITE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','MESSAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','NOTIFICATIONS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','ADD_FRIEND_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','NEW_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','LIKE_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','TIMELINE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','COMMENT_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','PROFILE_INFO_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','FRIENDS_FUNCTIONALITY',1)
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','SEARCH_GARAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','SEARCH_CLINICS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','SEARCH_CONSTRUCTIONCOMPANIES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','SEARCH_APPLIANCEREPAIR_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','SEARCH_INSURANCECONTACTS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','SETTINGS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('2','CURRENT_DISCUSSIONS_FUNCTIONALITY',1);

/* INSURANCE_PROFESSIONAL */
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','USERS_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','ROLES_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','ALERTS_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','COMPANY_FAVORITE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','MESSAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','NOTIFICATIONS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','ADD_FRIEND_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','NEW_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','LIKE_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','TIMELINE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','COMMENT_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','PROFILE_INFO_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','FRIENDS_FUNCTIONALITY',1)
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','SEARCH_GARAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','SEARCH_CLINICS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','SEARCH_CONSTRUCTIONCOMPANIES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','SEARCH_APPLIANCEREPAIR_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','SEARCH_INSURANCECONTACTS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','SETTINGS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('3','CURRENT_DISCUSSIONS_FUNCTIONALITY',1);

/* ASSOCIATED_PREMIUM */
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','USERS_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','ROLES_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','ALERTS_MANAGEMENT',0);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','COMPANY_FAVORITE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','MESSAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','NOTIFICATIONS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','ADD_FRIEND_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','NEW_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','LIKE_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','TIMELINE_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','COMMENT_POST_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','PROFILE_INFO_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','FRIENDS_FUNCTIONALITY',1)
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','SEARCH_GARAGES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','SEARCH_CLINICS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','SEARCH_CONSTRUCTIONCOMPANIES_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','SEARCH_APPLIANCEREPAIR_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','SEARCH_INSURANCECONTACTS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','SETTINGS_FUNCTIONALITY',1);
INSERT INTO [dbo].[AspNetRolesFunctionalities] ([RoleId],[Token],[Active]) VALUES ('4','CURRENT_DISCUSSIONS_FUNCTIONALITY',1);
