
DECLARE @companyTypeId bigint;

SELECT @companyTypeId = ID FROM [Insurance].[CompanyType] WHERE Token='GARAGE';

INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'A/C e Climatização', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Amortecedores', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Baterias', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Caixas de Velocidades', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Check-Up', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Correias de Distribuição', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Escapes', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Inspeção Periódica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Lavagem e Aspiração', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Loja de Peças', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Montagem/Assistência GPL', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Mudança de Óleo', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Pneus', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Reparação/Troca de Vidros', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Revisão', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Serviços de Bate-Chapa', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Serviços de Eletricista', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Serviços de Mecânica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Serviços de Pintura', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Sistemas Audio/Navegação', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Sistemas de Alarme', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Travões', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Troca de Filtros', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Tuning e Jantes', 1);

SELECT @companyTypeId = ID FROM [Insurance].[CompanyType] WHERE Token='MEDICAL_CLINIC';

INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Anatomia Patológica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Anestesiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Angiologia e Cirurgia Vascular', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cardiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cardiologia Pediátrica', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Centro de Fisioterapia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Cardiotorácica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Geral', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Maxilo-Facial', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Pediátrica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Plástica Reconstrutiva e Estética', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Dermato-Venereologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Doenças Infecciosas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Endocrinologia e Nutrição', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Estomatologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Angiologia e Cirurgia Vascular', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Cardiologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Cardiologia Pediátrica', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Dermatologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Gastrenterologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Ginecologia/Obstetricia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Imunoalergologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Neurofisiologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Oftalmologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Otorrinolaringologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Pneumologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Urologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Farmacologia Clínica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Gastrenterologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Genética Médica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Ginecologia/Obstetricia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Hematologia Clínica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Hepatologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Hospital', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Imunoalergologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Imunohemoterapia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Implantologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Odontologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Ortodontia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Radiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Desportiva', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina do Trabalho', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Fisica e de Reabilitação', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Geral e Familiar', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Intensiva', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Interna', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Legal', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Nuclear', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Tropical', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Nefrologia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Nefrologia Pediátrica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurocirurgia', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurofisiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurorradiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Oftalmologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Oncologia Médica', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Ópticas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Ortopedia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Otorrinolaringologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Patologia Clínica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Pediatria', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Pneumologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Psiquiatria', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Psiquiatria da Infância e da Adolescência', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Radiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Radioncologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Reumatologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Saúde e Bem estar', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Saúde Pública', 1);
--INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Terapia da Fala', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Urologia', 1);

