
DECLARE @companyTypeId bigint;

SELECT @companyTypeId = ID FROM [Insurance].[CompanyType] WHERE Token='GARAGE';

INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'acessórios', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'adesivos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'aditivos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'amortecedores e molas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'áudio e multimédia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'baterias', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'bombas de água', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'borracha-metal', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'caixas de velocidades', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'car care', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'categorias', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'centralinas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'climatização', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'correias e polias', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'direção e suspensão', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'eletrónica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'embraiagens', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'equipamentos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'escapes e emissões', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'escovas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'ferramentas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'filtros', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'iluminação', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'injeção', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'juntas e pernos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'líquido de travões', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'lubrificantes de motor', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'módulos de potência', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'motores de arranque e alternadores', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'motores reconstruídos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'peças de motor', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'pesos de equilíbrio', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'pneus', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'polímero de equilíbrio', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'radiadores', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'redes de oficinas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'reparação de pneus', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'repintura e carroçaria', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'rolamentos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'sensores', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'software oficinal', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'sondas lambda', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'transmissões', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'travões', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'tubos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'turbos', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Uncategorized', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'velas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'vidro automóvel', 1);

SELECT @companyTypeId = ID FROM [Insurance].[CompanyType] WHERE Token='MEDICAL_CLINIC';

INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Anatomia Patológica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Anestesiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Angiologia e Cirurgia Vascular', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cardiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cardiologia Pediátrica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Centro de Fisioterapia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Cardio-Torácica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Geral', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Maxilo-Facial', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Pediátrica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Cirurgia Plástica Reconstrutiva e Estética', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Dermatologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Doenças Infecciosas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Endocrinologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Enfermagem', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Angiologia e Cirurgia Vascular', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Cardiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Cardiologia Pediátrica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Dermatologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Gastrenterologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Ginecologia/Obstetricia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Imunoalergologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Neurofisiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Oftalmologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Otorrinolaringologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Pneumologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Exames Urologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Gastrenterologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Genética Médica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Ginecologia/Obstetricia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Hematologia Clínica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Hepatologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Hospital', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Imunoalergologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Imunohemoterapia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Implantologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Odontologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Ortodontia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Dentária - Radiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Desportiva', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Fisica e de Reabilitação', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Geral e Familiar (Clinica Geral)', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Interna', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Medicina Nuclear', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Nefrologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Nefrologia Pediátrica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurocirurgia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurofisiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Neurorradiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Oftalmologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Oncologia Médica', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Ópticas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Ortopedia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Otorrinolaringologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Patologia Clinica/Análises Clinicas', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Pediatria', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Pneumologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Psiquiatria', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Psiquiatria da Infância e da Adolescência', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Radiologia/Imagiologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Radioterapia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Reumatologia', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Serviço de Atendimento Permanente Geral', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Serviço de Atendimento Permanente Pediátrico', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Terapia da Fala', 1);
INSERT INTO Insurance.CompanyService ([ID_CompanyType],[Description],[Active]) VALUES (@companyTypeId, 'Urologia', 1);

