
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 6, 'Castelo de Paiva');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 7, 'Espinho');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 8, 'Estarreja');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 9, 'Santa Maria da Feira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 10, 'Ílhavo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 11, 'Mealhada');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 12, 'Murtosa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 13, 'Oliveira de Azeméis');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 14, 'Oliveira do Bairro');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 15, 'Ovar');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 16, 'São João da Madeira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 17, 'Sever do Vouga');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 18, 'Vagos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 19, 'Vale de Cambra');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 1, 'Águeda');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 2, 'Albergaria-a-Velha');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 3, 'Anadia');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 4, 'Arouca');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (1, 5, 'Aveiro');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 6, 'Castro Verde');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 7, 'Cuba');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 8, 'Ferreira do Alentejo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 9, 'Mértola');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 10, 'Moura');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 11, 'Odemira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 12, 'Ourique');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 13, 'Serpa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 14, 'Vidigueira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 1, 'Aljustrel');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 2, 'Almodôvar');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 3, 'Alvito');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 4, 'Barrancos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (2, 5, 'Beja');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 6, 'Esposende');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 7, 'Fafe');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 8, 'Guimarães');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 9, 'Póvoa de Lanhoso');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 10, 'Terras de Bouro');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 11, 'Vieira do Minho');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 12, 'Vila Nova de Famalicão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 13, 'Vila Verde');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 14, 'Vizela');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 1, 'Amares');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 2, 'Barcelos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 3, 'Braga');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 4, 'Cabeceiras de Basto');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (3, 5, 'Celorico de Basto');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 6, 'Miranda do Douro');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 7, 'Mirandela');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 8, 'Mogadouro');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 9, 'Torre de Moncorvo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 10, 'Vila Flor');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 11, 'Vimioso');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 12, 'Vinhais');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 1, 'Alfândega da Fé');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 2, 'Bragança');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 3, 'Carrazeda de Ansiães');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 4, 'Freixo de Espada à Cinta');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (4, 5, 'Macedo de Cavaleiros');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 6, 'Oleiros');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 7, 'Penamacor');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 8, 'Proença-a-Nova');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 9, 'Sertã');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 10, 'Vila de Rei');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 11, 'Vila Velha de Ródão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 1, 'Belmonte');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 2, 'Castelo Branco');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 3, 'Covilhã');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 4, 'Fundão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (5, 5, 'Idanha-a-Nova');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 6, 'Góis');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 7, 'Lousã');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 8, 'Mira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 9, 'Miranda do Corvo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 10, 'Montemor-o-Velho');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 11, 'Oliveira do Hospital');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 12, 'Pampilhosa da Serra');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 13, 'Penacova');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 14, 'Penela');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 15, 'Soure');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 16, 'Tábua');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 17, 'Vila Nova de Poiares');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 1, 'Arganil');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 2, 'Cantanhede');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 3, 'Coimbra');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 4, 'Condeixa-a-Nova');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (6, 5, 'Figueira da Foz');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 6, 'Montemor-o-Novo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 7, 'Mora');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 8, 'Mourão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 9, 'Portel');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 10, 'Redondo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 11, 'Reguengos de Monsaraz');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 12, 'Vendas Novas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 13, 'Viana do Alentejo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 14, 'Vila Viçosa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 1, 'Alandroal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 2, 'Arraiolos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 3, 'Borba');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 4, 'Estremoz');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (7, 5, 'Évora');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 6, 'Lagoa (Algarve)');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 7, 'Lagos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 8, 'Loulé');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 9, 'Monchique');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 10, 'Olhão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 11, 'Portimão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 12, 'São Brás de Alportel');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 13, 'Silves');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 14, 'Tavira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 15, 'Vila do Bispo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 16, 'Vila Real de Santo António');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 1, 'Albufeira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 2, 'Alcoutim');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 3, 'Aljezur');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 4, 'Castro Marim');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (8, 5, 'Faro');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 6, 'Gouveia');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 7, 'Guarda');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 8, 'Manteigas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 9, 'Meda');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 10, 'Pinhel');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 11, 'Sabugal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 12, 'Seia');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 13, 'Trancoso');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 14, 'Vila Nova de Foz Côa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 1, 'Aguiar da Beira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 2, 'Almeida');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 3, 'Celorico da Beira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 4, 'Figueira de Castelo Rodrigo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (9, 5, 'Fornos de Algodres');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 6, 'Caldas da Rainha');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 7, 'Castanheira de Pêra');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 8, 'Figueiró dos Vinhos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 9, 'Leiria');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 10, 'Marinha Grande');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 11, 'Nazaré');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 12, 'Óbidos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 13, 'Pedrógão Grande');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 14, 'Peniche');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 15, 'Pombal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 16, 'Porto de Mós');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 1, 'Alcobaça');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 2, 'Alvaiázere');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 3, 'Ansião');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 4, 'Batalha');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (10, 5, 'Bombarral');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 6, 'Lisboa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 7, 'Loures');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 8, 'Lourinhã');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 9, 'Mafra');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 10, 'Oeiras');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 11, 'Sintra');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 12, 'Sobral de Monte Agraço');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 13, 'Torres Vedras');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 14, 'Vila Franca de Xira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 15, 'Amadora');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 16, 'Odivelas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 1, 'Alenquer');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 2, 'Arruda dos Vinhos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 3, 'Azambuja');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 4, 'Cadaval');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (11, 5, 'Cascais');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 6, 'Crato');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 7, 'Elvas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 8, 'Fronteira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 9, 'Gavião');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 10, 'Marvão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 11, 'Monforte');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 12, 'Nisa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 13, 'Ponte de Sor');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 14, 'Portalegre');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 15, 'Sousel');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 1, 'Alter do Chão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 2, 'Arronches');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 3, 'Avis');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 4, 'Campo Maior');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (12, 5, 'Castelo de Vide');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 6, 'Maia');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 7, 'Marco de Canaveses');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 8, 'Matosinhos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 9, 'Paços de Ferreira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 10, 'Paredes');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 11, 'Penafiel');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 12, 'Porto');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 13, 'Póvoa de Varzim');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 14, 'Santo Tirso');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 15, 'Valongo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 16, 'Vila do Conde');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 17, 'Vila Nova de Gaia');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 18, 'Trofa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 1, 'Amarante');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 2, 'Baião');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 3, 'Felgueiras');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 4, 'Gondomar');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (13, 5, 'Lousada');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 6, 'Cartaxo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 7, 'Chamusca');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 8, 'Constância');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 9, 'Coruche');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 10, 'Entroncamento');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 11, 'Ferreira do Zêzere');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 12, 'Golegã');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 13, 'Mação');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 14, 'Rio Maior');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 15, 'Salvaterra de Magos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 16, 'Santarém');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 17, 'Sardoal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 18, 'Tomar');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 19, 'Torres Novas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 20, 'Vila Nova da Barquinha');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 21, 'Ourém');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 1, 'Abrantes');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 2, 'Alcanena');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 3, 'Almeirim');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 4, 'Alpiarça');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (14, 5, 'Benavente');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 6, 'Moita');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 7, 'Montijo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 8, 'Palmela');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 9, 'Santiago do Cacém');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 10, 'Seixal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 11, 'Sesimbra');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 12, 'Setúbal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 13, 'Sines');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 1, 'Alcácer do Sal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 2, 'Alcochete');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 3, 'Almada');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 4, 'Barreiro');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (15, 5, 'Grândola');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 6, 'Ponte da Barca');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 7, 'Ponte de Lima');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 8, 'Valença');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 9, 'Viana do Castelo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 10, 'Vila Nova de Cerveira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 1, 'Arcos de Valdevez');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 2, 'Caminha');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 3, 'Melgaço');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 4, 'Monção');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (16, 5, 'Paredes de Coura');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 5, 'Mondim de Basto');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 6, 'Montalegre');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 7, 'Murça');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 8, 'Peso da Régua');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 9, 'Ribeira de Pena');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 10, 'Sabrosa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 11, 'Santa Marta de Penaguião');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 12, 'Valpaços');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 13, 'Vila Pouca de Aguiar');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 14, 'Vila Real');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 1, 'Alijó');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 2, 'Boticas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 3, 'Chaves');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (17, 4, 'Mesão Frio');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 5, 'Lamego');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 6, 'Mangualde');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 7, 'Moimenta da Beira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 8, 'Mortágua');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 9, 'Nelas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 10, 'Oliveira de Frades');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 11, 'Penalva do Castelo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 12, 'Penedono');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 13, 'Resende');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 14, 'Santa Comba Dão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 15, 'São João da Pesqueira');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 16, 'São Pedro do Sul');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 17, 'Sátão');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 18, 'Sernancelhe');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 19, 'Tabuaço');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 20, 'Tarouca');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 21, 'Tondela');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 22, 'Vila Nova de Paiva');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 23, 'Viseu');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 24, 'Vouzela');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 1, 'Armamar');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 2, 'Carregal do Sal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 3, 'Castro Daire');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (18, 4, 'Cinfães');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 5, 'Ponta do Sol');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 6, 'Porto Moniz');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 7, 'Ribeira Brava');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 8, 'Santa Cruz');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 9, 'Santana');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 10, 'São Vicente');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 1, 'Calheta (Madeira)');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 2, 'Câmara de Lobos');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 3, 'Funchal');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (31, 4, 'Machico');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (32, 1, 'Porto Santo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (41, 1, 'Vila do Porto');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (42, 5, 'Ribeira Grande');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (42, 6, 'Vila Franca do Campo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (42, 1, 'Lagoa (São Miguel)');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (42, 2, 'Nordeste');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (42, 3, 'Ponta Delgada');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (42, 4, 'Povoação');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (43, 1, 'Angra do HeroÃ­smo');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (43, 2, 'Praia da Vitória');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (44, 1, 'Santa Cruz da Graciosa');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (45, 1, 'Calheta (São Jorge)');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (45, 2, 'Velas');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (46, 1, 'Lajes do Pico');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (46, 2, 'Madalena');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (46, 3, 'São Roque do Pico');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (47, 1, 'Horta');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (48, 1, 'Lajes das Flores');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (48, 2, 'Santa Cruz das Flores');
INSERT INTO Insurance.County ([District_Code],[Code],[Name]) VALUES (49, 1, 'Corvo');