

INSERT INTO Insurance.District ([Code],[Name]) VALUES (1, 'Aveiro');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (2, 'Beja');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (3, 'Braga');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (4, 'Bragança');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (5, 'Castelo Branco');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (6, 'Coimbra');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (7, 'Évora');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (8, 'Faro');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (9, 'Guarda');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (10, 'Leiria');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (11, 'Lisboa');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (12, 'Portalegre');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (13, 'Porto');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (14, 'Santarém');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (15, 'Setúbal');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (16, 'Viana do Castelo');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (17, 'Vila Real');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (18, 'Viseu');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (31, 'Ilha da Madeira');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (32, 'Ilha de Porto Santo');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (41, 'Ilha de Santa Maria');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (42, 'Ilha de São Miguel');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (43, 'Ilha Terceira');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (44, 'Ilha da Graciosa');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (45, 'Ilha de São Jorge');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (46, 'Ilha do Pico');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (47, 'Ilha do Faial');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (48, 'Ilha das Flores');
INSERT INTO Insurance.District ([Code],[Name]) VALUES (49, 'Ilha do Corvo');