using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InsuranceSocialNetworkCore.Enums
{
    public enum RoleEnum
    {
        ADMINISTRATOR,
        NORMAL_USER,
        INSURANCE_PROFESSIONAL,
        ASSOCIATED_PREMIUM,
        DIRECTORY_COMPANY,
        PORTAL_COMMERCIAL
    }

    public enum Functionality
    {
        USERS_MANAGEMENT,
        ROLES_MANAGEMENT,
        ALERTS_MANAGEMENT,
        BANNERS_MANAGEMENT,
        COMPANIES_MANAGEMENT,
        COMPANY_FAVORITE_FUNCTIONALITY,
        MESSAGES_FUNCTIONALITY,
        NOTIFICATIONS_FUNCTIONALITY,
        ADD_FRIEND_FUNCTIONALITY,
        NEW_POST_FUNCTIONALITY,
        LIKE_POST_FUNCTIONALITY,
        TIMELINE_FUNCTIONALITY,
        COMMENT_POST_FUNCTIONALITY,
        PROFILE_INFO_FUNCTIONALITY,
        FRIENDS_FUNCTIONALITY,
        SEARCH_GARAGES_FUNCTIONALITY,
        SEARCH_CLINICS_FUNCTIONALITY,
        SEARCH_CONSTRUCTIONCOMPANIES_FUNCTIONALITY,
        SEARCH_APPLIANCEREPAIR_FUNCTIONALITY,
        SEARCH_INSURANCECONTACTS_FUNCTIONALITY,
        SETTINGS_FUNCTIONALITY,
        CURRENT_DISCUSSIONS_FUNCTIONALITY,
        NEW_CURRENT_DISCUSSION_FUNCTIONALITY,
        APS_FUNCTIONALITY,
        NEW_APS_FUNCTIONALITY,
        ASF_FUNCTIONALITY,
        NEW_ASF_FUNCTIONALITY,
        APROSE_FUNCTIONALITY,
        NEW_APROSE_FUNCTIONALITY
    }
}
